#Programmed by guofeifei, used for hierarchical clustering
#usage: Rscript hclu.r simMatrix-test.csv clu-test.pdf
#input: simMatrix-test.csv which were generated by extracRelation.pl
#ouput: clu-test.pdf 
library(ape)
params<-commandArgs(trailingOnly=TRUE)
inputfile=params[1] #input file
outfile=params[2] #output file
mat<-read.table(inputfile) #read data matrix
hc <- hclust(as.dist(mat),method="complete") # saperate data into xxx cluster
#hcd = as.dendrogram(hc)
hcd = as.phylo(hc)
ad=paste(getwd(),outfile,sep='/')
pdf(ad,width=8, height=8)#set the size of paint
plot(hcd)
dev.off()